### ISSUE TITLE
parameters in TuckER

### ISSUE THREAD

**Issue by Re-fused** [Peyman-Bi/SAttLE#1]
Hello, recently I am conducting SAttLE experiment based on TuckER, but the effect is not particularly good, you can share the parameters in TuckER.

**Comment by pbaghershahi** [comment]
Hi,
Please refer to the paper, you'd find all the experimental setting results available in appendix A.2. Here is the table of this section.

<img width="1209" alt="SCR-20240329-fjsc" src="https://github.com/pbaghershahi/SAttLE/assets/53485188/3418b2b5-40f1-4913-966d-2299aa71c444">
